#!/bin/bash
# Helper script to set API environment variables
# Usage: ./ops/set_api_env.sh <env> [commit_sha]
# Example: ./ops/set_api_env.sh prod abc1234

set -e

ENV="${1:-dev}"
COMMIT_SHA="${2:-$(git rev-parse --short HEAD 2>/dev/null || echo 'local-dev')}"

if [[ ! "$ENV" =~ ^(prod|sim|demo|dev)$ ]]; then
    echo "❌ Error: Environment must be one of: prod, sim, demo, dev"
    echo "Usage: $0 <env> [commit_sha]"
    exit 1
fi

echo "🔧 Setting API environment variables:"
echo "   F90_ENV=$ENV"
echo "   F90_API_VERSION=v1"
echo "   F90_COMMIT_SHA=$COMMIT_SHA"
echo ""

# Export for current shell
export F90_ENV="$ENV"
export F90_API_VERSION="v1"
export F90_COMMIT_SHA="$COMMIT_SHA"

# Create .env file snippet
cat > .env.api <<EOF
# API Environment Configuration
# Generated by: $0 $ENV $COMMIT_SHA
# Date: $(date -u +"%Y-%m-%dT%H:%M:%SZ")

F90_ENV=$ENV
F90_API_VERSION=v1
F90_COMMIT_SHA=$COMMIT_SHA
EOF

echo "✅ Environment variables exported to current shell"
echo "✅ Saved to .env.api file"
echo ""
echo "To use with docker-compose:"
echo "  docker compose --env-file .env.api up -d api"
echo ""
echo "To use in current shell:"
echo "  source <($0 $ENV $COMMIT_SHA)"
echo "  # or"
echo "  export F90_ENV=$ENV"
echo "  export F90_API_VERSION=v1"
echo "  export F90_COMMIT_SHA=$COMMIT_SHA"

